#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $DEVIL_REPO == "whitedevilbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $DEVIL_REPO == "whitedevilbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $DEVIL_REPO =~ $regex ]]
    then
        if [[ $DEVIL_REPO_BRANCH ]]
        then
            echo "${DEVIL_REPO}/archive/${DEVIL_REPO_BRANCH}.zip"
        else
            echo "${DEVIL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="whitedevilbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    MAFIAPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $DEVILPATH
    echo "    Starting whitedevil    "
    echo "
           ██╗────██╗
           ██║────██║
           ██║─█╗─██║
           ██║███╗██║
            ╚██╔███╔╝
           ─╚══╝╚══╝
             ██████╗
             ██╔══██╗
             ██████╔╝
             ██╔══██╗
             ██████╔╝
             ╚═════╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m whitedevil
}

_set_bot
